### ISSUE TITLE
LabRecorder broken?

### ISSUE THREAD

**Issue by dmedine** [sccn/labstreaminglayer#68]
All of a sudden I've been having trouble with LabRecorder. It seems that recent changes to pylsl.py may have broken these lines (78-282):

            # determine the streams to record from...
            stream_array = c_void_p*len(into_streams)
            #streams = [c_void_p(s.handle()) for s in into_streams]
            streams = [c_void_p(s.obj) for s in into_streams]
            streams = stream_array(*streams)

When I hit record, it breaks on line 281 reporting the following error:

Traceback (most recent call last):
  File "D:/lsl-dev/labstreaminglayer/Apps/LabRecorder/src/LabRecorder.py", line 281, in startRecording
    streams = [c_void_p(s.obj) for s in into_streams]
TypeError: cannot be converted to pointer

Sascha Frydman has noted that changing line 281 so that it reads

            streams = [s.obj for s in into_streams]

will put an end to this bug, but it brings up others. With this change, LabRecorder will crash when (after recording for a while) the Update button is hit. It throws me different errors depending on the order in which I do things to crash it, but the most reliable looking error concerns pylsl:

Traceback (most recent call last):
  File "D:/lsl-dev/labstreaminglayer/Apps/LabRecorder/src/LabRecorder.py", line 157, in refreshStreams
    self.ResolvedStreams = list(pylsl.resolve_streams(1.0))
  File "D:\lsl-dev\labstreaminglayer\Apps\LabRecorder\src\pylsl\pylsl.py", line 518, in resolve_streams
    num_found = lib.lsl_resolve_all(byref(buffer), 1024, c_double(wait_time))
WindowsError: exception: access violation reading 0x72657334

Which presumably has to do with lines 517-519:
    buffer = (c_void_p*1024)()
    num_found = lib.lsl_resolve_all(byref(buffer), 1024, c_double(wait_time))
    return [StreamInfo(handle=buffer[k]) for k in range(num_found)]

To me the python/C++ thing is all black magic, so I could be way off. I certainly have no idea how to debug something like this, so I'm kind of grasping at straws here.

**Comment by chkothe** [comment]
The LabRecorder used to ship its own version of pylsl, that hopefully still
works. However, I made a new feature branch to test a new version of the
recorder that has been cleaned up to work with Python 3 and current pylsl
-- do you get the same error on there?

**Comment by dmedine** [comment]
Hmmm. This is getting very mysterious. First of all, I didn't realize the revisions to pylsl were not in the main branch. This is why I thought something had changed there. Secondly, in the course of re-running some experiments just a few minutes after posting the last issue, LabRecorder appears to be working normally. I will definitely investigate this further tomorrow. 

I will also check the new branch and test the new version out.

**Comment by chkothe** [comment]
Yeah, I actually have pylsl currently under https://github.com/chkothe/pylsl.
We could roll it into the sccn repo, but we'd need to make sure to push the
updated package up to Python's package index. In fact, I'm behind with
pushing the latest round of updates due to a bunch of other deadlines.

**Comment by sandymacpherson** [comment]
Has there been any resolution to this? I have tried running the LabRecorder on Mac and Windows and both suffer from the exception described by dmedine at the start of this issue. Making the suggested change seems to work, but I am worried about unexpected consequences.

**Comment by dmedine** [comment]
I have not had a chance to delve seriously into this. I have been using the latest version of LabRecorder and LSL for Windows and it is rock solid except if a recording is stopped and then started again. Obviously this needs to be fixed, but for the present, you can be confident in your recording provided it doesn't stop and start midway through. I will push this up my queue of things to work on.

**Comment by chkothe** [comment]
In the meantime it is probably best to use a stable version from the ftp
mirror. David, is this issue only present in the trunk, or is the latest
app download also affected?

**Comment by dmedine** [comment]
Apparently it is all affected. I just downloaded each of the 3 versions on the ftp and none of them worked properly. The most recent release (1.11) gives the infamous error on line 281:

streams=[c_void_p(s.obj) for s in into_streams]
TypeError:cannot be converted to pointer

The older versions hang on loading LSL:

AttributeError: 'module' object has no attribute 'resolve_streams'

I'm not sure why older, stable versions are all of a sudden broken. I am still using Windows 7 and 32-bit Python 2.7 (as has always been the case).

**Comment by chkothe** [comment]
If you have pylsl in your python installation it might (wrongly) take
precedence over the one that comes with the recorder.

**Comment by dmedine** [comment]
Unfortunately, I am not sure what I did to make this work, but I am convinced that labrecorder on Windows 7 is rock solid now. I did change line 281 as discussed above, but now it seems to behave correctly every time. I am in the midst of establishing this on Linux and Mac. I will then close the issue.

**Comment by dmedine** [comment]
The latest update is that LabRecorder now works on Windows and Linux without issue. Yesterday I pushed a makefile to rebuild RecorderLib on Linux which was necessary. We still have no joy on OSX. There is a deadly segmentation fault when closing streams. I can post the backtrace if anyone is interested. 

Next week (if I have time) I will start experimenting with the experimental pylsl branches.

**Comment by dmedine** [comment]
So I did track down the bug in closing labrecorder under osx. 

It appears that for some reason, in recorder object (defined in recording.h -- part of recorder lib), the mutex lock called phase_mut_ gets bashed out somewhere along the way and ends up having a void member when the recorder object is being destroyed. 

This lock is used to ensure thread safety a number of times when recording begins (for example line 605 of recorder.h). Stepping through the code, we see that it has a reasonable value (12987837 or some such thing) for the phase_mut_->m->_sig member. When recording is stopped, this lock is locked again in order to safely switch the shutdown_ flag, but at this point phase_mut_->m->_sig is empty. XCode won't let me watch this value, so I'm not sure how to proceed. 

This is pretty gnarly C++, boost stuff. If anybody knows how to deal with this, I would love to know that. A cursory glance at boost discussions don't give many clues.

**Comment by cboulay** [comment]
Hi David,

Do you have a pylsl that works completely in Win/Linux and works mostly in OS X with the exception of crashing when closing LabRecorder?

I'd like to do a system install of pylsl. If I use `pip install pylsl` or if I do `python setup.py install` from within the latest LSL/liblsl-Python folder, the result is a non-functioning pylsl that seg faults almost immediately in OS X.

**Comment by chkothe** [comment]
Hi Chad, due to the way in which the LabRecorder is currently implemented,
it cannot be used with a systemwide pylsl installation, because the pylsl
version can't be guaranteed to match the recorderlib's linked liblsl
version (but they need to be identical because handles to internal data
structures are being passed between them). We've been contemplating a
rewrite of either the recorder in C++ or recorderlib in python to fix this,
and concluded that LabRecorder in C++ will be best for users, but it'll
take us (David) another week or two to get around to it.

Christian

Hi David,

Do you have a pylsl that works completely in Win/Linux and works mostly in
OS X with the exception of crashing when closing LabRecorder?

I'd like to do a system install of pylsl. If I use pip install pylsl or if
I do python setup.py install from within the latest LSL/liblsl-Python
folder, the result is a non-functioning pylsl that seg faults almost
immediately in OS X.

—
Reply to this email directly or view it on GitHub
<https://github.com/sccn/labstreaminglayer/issues/68#issuecomment-175664371>
.

**Comment by cboulay** [comment]
OK that's good to know, thank you.

I'm still getting seg faults in regular pylsl scripts (i.e., NOT LabRecorder) when using the supplied pylsl. My modified version of pylsl works with in these cases but was ultimately abandoned because it creates undesirable behaviour in Windows (and Linux?), and it still results in seg faults in OS X when closing LabRecorder.

IIRC, David had taken the original pylsl (which worked correctly in Win/Linux) and modified it somewhat so it worked in OS X with the exception of the LabRecorder crashes, as detailed above. This version of pylsl would be acceptable for me now, but I don't know where to find it. The pylsl that comes with the master fork does not work at all in OS X.

**Comment by dmedine** [comment]
I will check this out. Last time I used it, pylsl worked on Yosemite on 
Python2.7 (64-bit, ofcourse), but this was in an attempt to better 
understand the conflicts in LabRecorder and may have used a fresh build 
of LSL on OSX (although that should be the same as the one on the ftp 
anyway -- so I don't know what the problem might be).

Give me a day or two to get around to this -- we're in the midst of a 
time-sensitive moving operation at the lab right now, but when it's done 
I will see what I can see.
Cheers,
David

**Comment by chkothe** [comment]
Not sure if this helps, but I've seen a report that pylsl on Linux would
segfault when used on a non-master thread; I haven't yet been able to
investigate this, but given the similarity between the two operating
systems, the same issue might also occur on OSX. This is really quite
interesting since the py part in pylsl is rather tiny and doesn't leave
much room for bugs (and liblsl itself has been rock solid on any OS we've
so far tested it on).

Christian

**Comment by chkothe** [comment]
PS: For this reason I think a very low-level interference between the
Python runtime and liblsl's network backend might be the cause (e.g.,
perhaps some per-process setting that Python sets and boost.asio stumbles
over, which could plausibly also affect OSX). The only other thing that I
can think of are the usual Python/C 32/64 bit marshaling problems, but I
chances are that we've caught all of those.

**Comment by dmedine** [comment]
I'm just getting back into LSL land after a week+ of other pressing 
matters here at the lab.

I just fired up Yoseimte 10.10.5, cloned 
https://gitub.com/sccn/labstreaminglayer, ran get_deps.py and the only 
thing that seems to crash in the example programs for pylsl is in 
SendDataAdvanced.py For some reason we get segmentation errors related 
to the pugi::xml code.

I know this library has been updated a number of times since the version 
that still sits within LSL. It might be worth the time to rebuild with a 
newer version. I suspect, though, that this may not help.

Has anyone tried pylsl on OSX with 32-bit python?

Linux is unavailable to me at the moment.
Cheers,
David

**Comment by cboulay** [comment]
How did you add pylsl to the path when running those examples? Or did you `python setup.py install` from within the pylsl folder?

If I do the latter then I have the same results as you. Unfortunately, all of my production pylsl programs still crash because they make use of the XML data (e.g., `info_xml.append_child("channel")`)

I couldn't build lsl in OS X using the supplied project. Every target I try to build gives me the error `The run destination My Mac is not valid for Running scheme '<target name>'`. However, I was able to use cmake. By default, the current project doesn't build because it fails on pugixml. So I overwrote the files using the latest from the [pugixml repo](https://github.com/zeux/pugixml). It builds! Of course, the built library has the wrong name and wrong path id, so I did the following:

```
mv liblsl.dylib liblsl64.dylib
install_name_tool -id "@rpath/liblsl64.dylib" liblsl64.dylib
```

I then tried to run my programs again. They still segfault on the info_xml commands, but not otherwise. :(

I'll take a look at the differences between my pylsl.py and the latest from this repo to see if I can narrow down the changes to find something that allows this to work without breaking pylsl in Windows.

**Comment by cboulay** [comment]
I tracked it down to 2 lines that must be added to pylsl.py to get it working in OS X with SendDataAdvanced.py

```
lib.lsl_append_child_value.argtypes = [c_void_p, c_char_p, c_char_p]
lib.lsl_append_child.argtypes = [c_void_p, c_char_p]
```

I'll make a pull request after I test that this doesn't break Windows.

**Comment by dmedine** [comment]
I simply add the pylsl directory to my PYTHONPATH environment variable. 
This is fine in both Windows and Unix-ish environments, although the 
methods are different.

**Comment by dmedine** [comment]
Just tried this and it definitely crashes on Windows. I get

TypeError: restype must be a type, a callable, or None

**Comment by cboulay** [comment]
I just tried it on Windows before making the pull request and it worked. Also, the above lines specify argtypes, not restype, so I don't see how they could cause that error. I'll check again.

**Comment by cboulay** [comment]
Using #81 , It works for me in both Windows 10, python 2.7 x64 and in OS X python 2.7. I don't think 64/32-bit is a thing anymore in OS X because I think Python uses universal binaries.

Can you give me more info about how you set it up and how you are able to produce the error?

**Comment by dmedine** [comment]
C++ version of LabRecorder is now up and running and hopefully bug free at this point.
